name: Build and Publish ColabFold Docker

on:
  workflow_dispatch:
    inputs:
      colabfold_version:
        description: 'ColabFold Conda version'
        required: true
        type: string
        default: '1.5.5'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cuda_version: ["11.8.0", "12.2.2"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository name to lowercase
        run: echo "IMAGE_NAME_LOWER=$(echo ${{ env.IMAGE_NAME}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ github.event.inputs.colabfold_version }}-cuda${{ matrix.cuda_version }}
          platforms: linux/amd64 # ,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            COLABFOLD_VERSION=${{ github.event.inputs.colabfold_version }}
